default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: blood_sweat_beers_development

test:
  <<: *default
  database: blood_sweat_beers_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV.fetch("DATABASE_CACHE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV.fetch("DATABASE_QUEUE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("DATABASE_CABLE_URL", ENV["DATABASE_URL"]) %>
    migrations_paths: db/cable_migrate
